name: Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-rdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vemonet/jena-riot-action@v3.14
        with:
          input: nanowiki.ttl
